### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by scottjehl** [paulirish/matchMedia.js#66]
not currently on npm. we could improve the packaging exports and all but for starters, maybe bump the minor version and give it a unique name for npm like... "matchmedia-polyfill"?

**Comment by krnlde** [comment]
Absolutely. Do you think shipping it as a UMD would be a good idea to tackle different consumers?

**Comment by scottjehl** [comment]
That part I'm not sure about. This script is often inlined so, we'd just want to make sure it can still expose on `window` object by default as well, without a packager. Agree? Maybe worth another pass for this part...

**Comment by krnlde** [comment]
Absolutely, that's why I suggested the UMD pattern, which gracefully degrades to the global window object if no AMD module load is defined.

**Comment by scottjehl** [comment]
cool. might you have any time to work out a PR? If not I'll work on it at
some point here. Thanks!

**Comment by krnlde** [comment]
I'll try my best and implement this stuff with the https://github.com/umdjs/umd/blob/master/templates/commonjsStrict.js template. brb

**Comment by krnlde** [comment]
#68 there you go.

**Comment by krnlde** [comment]
Is skipped the commonJS wrapper for now, since this is mostly used in a Node environment - where matchMedia makes no sense. Or do I sth here?

**Comment by scottjehl** [comment]
Thanks @krnlde 

Looks nice. I think I'll merge PR 67 since it doesn't change the code any, and leave this open for discussion after that.

**Comment by iDVB** [comment]
Can someone add some install/usage details to the readme? I'm not entirely sure where/how this poly get used.  If I install via npm... .then do I simply...
`import 'matchmedia-polyfill'` at the first line of my application? what about other dependencies that might need it.

Why does the readme say "Used in: Modernizr" ? I'm including modernizr already..... do I have to include options.mq? Assuming that is where Modernizr is using it?  I've tried including the whole modernizr.min from cdn and still in IE9 if I window.matchmedia I get nothing back

**Comment by krnlde** [comment]
The package.json states that there are no other dependencies.
You should be able to just `import 'matchmedia-polyfill'` in your repo. Did you try it before writing?

**Comment by iDVB** [comment]
Yes. Still not working.

Either way, the readme docs could still use more detail. Especially considering that they said its used in Moderizr. I mean, I'm using Modernizr already, does that mean I don't need to include this directly? Which is contradicted but the Moderizr docs which make it look like the `Modernizr.matchMedia` can be polyfilled by including (this yet to be included) polyfill.

So between it not seeming to work in the simple expected way, and the documentation, its easy to loose a few hours to this. Just thought updating the readme might pay it forward.

Any ideas why my personal case is not working?

![Error](https://goo.gl/ZmWNmL)

**Comment by iDVB** [comment]
I "think" I know what the issue is. When I look at exactly what line the browser is complaining about, it appears its coming from a dep of a dep. ([enquire.js](https://github.com/WickyNilliams/enquire.js) of [react-slick](https://github.com/akiran/react-slick));

So I think enquire.js is is being loaded into a vendor chunk and somehow being loaded before the poly is implemented? Either that or the poly is not being setup properly? When I go into IE9 inspector after everything is loaded... I would expect that running `window.matchmedia` would return something, however it does not.

**Comment by krnlde** [comment]
I'm not sure what the `window` object really is in a node environment. Could be that browserify or whatever you use will prevent you from putting something in a non-existing context, i.e. `window`. In that case matchMedia should be appended to `global` instead of window object. Could you please try that in the node_modules/ code?

**Comment by iDVB** [comment]
I'm not aware of doing anything special. I'm using webpack to build, with babel for es2015.

My expectation is that this polyfill would still update the window object, no? But as I said, it does not seem to be since IE9 does not have this property off window. 

Is there a manual/inline way to include this poly just in a script tag or from a CDN? I feel like I'm missing something really basic here.

**Comment by krnlde** [comment]
Webpack is there for putting npm (node) modules on the browser side. Since there is now `window` object in node, it is most likely not working.

You could manually add the matchMedia.js before your bundled JS file, like so:

```html
<script src="path/to/matchMedia.js"></script>
<script src="yourWebpackBundle.js"></script>
```

**Comment by iDVB** [comment]
Might also have something to do with it. However, I did figure out my issue.
Turns out that I was including the poly in with my webpack chunk bundle (vendor) AFTER the react-slick one.  Although, that does not make sense to me why a simple code allocation would cause code to render in an order.  I guess react-slick or dep has got code that runs at inlcude time rather then instantiation.

Either way, problem solved once the poly was moved to the top of the array.

```javascript
module.exports = {
  entry: {
    app:[path.resolve(__dirname, 'app/app.js')],
    vendor: [
      'matchmedia-polyfill',
      "react",
      "react-dom",
      "react-router/lib/Router",
      "react-router/lib/browserHistory",
      "react-router/lib/Link",
      "react-router/lib/Route",
      "react-router/lib/IndexRedirect",
      "react-router/lib/Redirect",
      "react-bootstrap/lib/Navbar",
      "react-bootstrap/lib/Nav",
      "react-bootstrap/lib/NavItem",
      "react-router-bootstrap",
      "react-addons-transition-group",
      "classnames",
      "animation.gsap",
      "scrollmagic",
      "iscroll",
      "formsy-react",
      "lodash.throttle",
      "radium",
      "react-hammerjs",
      "react-iscroll",
      "react-portal",
      "react-select",
      "react-slick",
      "react-youtube",
      "vivus",
      "react-helmet",
      "modernizr",
      "TweenMax",
      "TimelineMax",
    ],
  },
```

**Comment by paulirish** [comment]
published 2 yrs ago. https://www.npmjs.com/package/matchmedia-polyfill
